---
api:
  sdpConfigdbHost: "ska-sdp-etcd.dp-shared"
  vault:
    useVault: true
    pathToSecretVault: phoenix/sdhp-stfc/staging/ska-sdp-dataproduct-api
  postgresql:
    host: "pgdev-lb.cnpgdev.svc.cluster.local"
    user: "sdp_sdp_dataproduct_dashboard_staging"
    dbname: "staging"
    schema: "sdp_sdp_dataproduct_dashboard_staging"

dashboard:
  vault:
    useVault: true
