---
# Enable/disable the Vault secret synchronization
# When enabled: secrets are synced from Vault using VaultStaticSecret resources
# When disabled: secrets must be managed externally (manually created or via other tools)
enabled: false

# Vault configuration
vault:
  engine: "dev"
  refreshAfter: 360s
  
# Secrets to sync from Vault
secrets:
  dashboard:
    vaultPath: "phoenix/sdhp-stfc/integration/ska-dataproduct-dashboard"
    # Name of the Kubernetes secret that will be created/synced
    secretName: "ska-dataproduct-dashboard-dashboard-secret"
    # Keys to extract from Vault secret
    keys:
      - REACT_APP_MSENTRA_CLIENT_ID
      - REACT_APP_MSENTRA_TENANT_ID
  
  api:
    vaultPath: "phoenix/sdhp-stfc/integration/ska-sdp-dataproduct-api"
    # Name of the Kubernetes secret that will be created/synced
    secretName: "ska-dataproduct-dashboard-api-secret"
    # Keys to extract from Vault secret
    keys:
      - SKA_DATAPRODUCT_API_POSTGRESQL_PASSWORD
